### ISSUE TITLE
Default java package version out of date

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/ansible-java#31]
Current default package version [here](https://github.com/azavea/ansible-java/blob/develop/defaults/main.yml#L2) is out of date.  See more recent version [here](https://github.com/azavea/ansible-opentripplanner/blob/develop/meta/main.yml#L21).

**Comment by hectcastro** [comment]
It looks like the defaults for the role are up-to-date, for the default OpenJDK flavor. The 8u151 version is for the Oracle JDK.
